### ISSUE TITLE
Cannot get maven-cuke4duke-jump-start to work....

### ISSUE THREAD

**Issue by mikesmithson** [cucumber-attic/cuke4duke#107]
Seem to be having issues trying to run the jump-start app. I tried upgrading the jruby-complete dependency to version 1.6.1, and got to this point when running mvn clean integration-tests. Any help?

[INFO] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'helloWorldSteps': Injection of autowired dependencies f
ailed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.mycompany.test.pageObjects.WebSite c
om.mycompany.test.features.HelloWorldSteps.webSite; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean w
ith name 'webSite' defined in file [C:\java\maven-cuke4duke-jump-start\target\test-classes\com\mycompany\test\pageObjects\WebSite.class]: Instantiatio
n of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.mycompany.test.pageO
bjects.WebSite]: Constructor threw exception; nested exception is java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException (Native
Exception)
[INFO] org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.java:285:in `postProcessPropertyValues'
[INFO] org/springframework/beans/factory/support/AbstractAutowireCapableBeanFactory.java:1074:in`populateBean'
[INFO] org/springframework/beans/factory/support/AbstractAutowireCapableBeanFactory.java:517:in `doCreateBean'
[INFO] org/springframework/beans/factory/support/AbstractAutowireCapableBeanFactory.java:456:in`createBean'
[INFO] org/springframework/beans/factory/support/AbstractBeanFactory.java:291:in `getObject'
[INFO] org/springframework/beans/factory/support/DefaultSingletonBeanRegistry.java:222:in`getSingleton'
[INFO] org/springframework/beans/factory/support/AbstractBeanFactory.java:288:in `doGetBean'
[INFO] org/springframework/beans/factory/support/AbstractBeanFactory.java:190:in`getBean'
[INFO] org/springframework/beans/factory/support/DefaultListableBeanFactory.java:580:in `preInstantiateSingletons'
[INFO] org/springframework/context/support/AbstractApplicationContext.java:895:in`finishBeanFactoryInitialization'
[INFO] org/springframework/context/support/AbstractApplicationContext.java:425:in `refresh'
[INFO] org/springframework/context/support/ClassPathXmlApplicationContext.java:139:in`<init>'
[INFO] org/springframework/context/support/ClassPathXmlApplicationContext.java:105:in `<init>'
[INFO] cuke4duke/internal/jvmclass/SpringFactory.java:43:in`addStepMother'
[INFO] cuke4duke/internal/jvmclass/ClassLanguage.java:32:in `<init>'
[INFO] cuke4duke/internal/jvmclass/ClassLanguage.java:25:in`<init>'
[INFO] sun/reflect/NativeConstructorAccessorImpl.java:-2:in `newInstance0'
[INFO] sun/reflect/NativeConstructorAccessorImpl.java:39:in`newInstance'
[INFO] sun/reflect/DelegatingConstructorAccessorImpl.java:27:in `newInstance'
[INFO] java/lang/reflect/Constructor.java:513:in`newInstance'
[INFO] org/jruby/javasupport/JavaConstructor.java:243:in `newInstanceDirect'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cuke4duke-0.4.3/bin/../lib/cucumber/class_support/class_language.rb:19:in`initialize'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime/support_code.rb:69:in `load_programming_language'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime/support_code.rb:190:in`programming_language_for'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime/support_code.rb:174:in `load_file'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime/support_code.rb:78:in`load_files!'
[INFO] org/jruby/RubyArray.java:1602:in `each'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime/support_code.rb:77:in`load_files!'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime.rb:137:in `load_step_definitions'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/runtime.rb:39:in`run!'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/cli/main.rb:43:in `execute!'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/lib/cucumber/cli/main.rb:20:in`execute'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/bin/cucumber:14:in `(root)'
[INFO] org/jruby/RubyKernel.java:1063:in`load'
[INFO] C:/Users/Mike Smithson/.m2/repository/.jruby/gems/cucumber-0.10.2/bin/cucumber:4:in `(root)'
[INFO] org/jruby/RubyKernel.java:1063:in`load'
[INFO] C:\Users\Mike Smithson.m2\repository.jruby\bin\cuke4duke:19:in `(root)'

**Comment by jamesladd** [comment]
Try downloading the cuke4duke maven project and building that with "mvn clean install",
then the jump start project with:
"mvn -Dcucumber.installGems=true cuke4duke:cucumber"
"mvn clean integration-test"

**Comment by Caelrin** [comment]
I am having this same issue. So far it looks to me like there is something wrong with starting selenium, which cascades into a spring injection error into cuke4duke not working. 

Has anyone found a solution to this?

**Comment by jamesladd** [comment]
When this has happened to me I have deleted the Maven repository folder,
and tried the full install and run again.
