### ISSUE TITLE
Errors while running java example "HelloCucumber"

### ISSUE THREAD

**Issue by kedarwaghmode** [cucumber-attic/cuke4duke#119]
Hi,

I am having trouble in running java example "HelloCucumber". I downloaded source code from https://github.com/cucumber/cuke4duke/tree/master/examples/java 
and trying to run it before I actually run my own java commands.When I try to run with maven like "mvn clean install" I get following error

---

---

failed to create task or type antlib:org.apache.ivy.ant:retrieve

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.563s
[INFO] Finished at: Tue Jul 12 15:07:59 PDT 2011
[INFO] Final Memory: 3M/122M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project HelloCucumber: Could not resolve depen
dencies for project HelloCucumber:HelloCucumber:jar:1.0: Failure to find cuke4du
ke:cuke4duke:jar:0.3.2 in http://repository.codehaus.org was cached in the local
 repository, resolution will not be reattempted until the update interval of cod
ehaus has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

---

While when I do it with ant like "ant -Divy=true -Dgems=true" I get following error,

---

-download-jars:

BUILD FAILED
..\src\java\HelloCucumber\build.xml:28: Problem: failed to create task 
or type antlib:org.apache.ivy.ant:retrieve
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration.
Action: Check that the implementing library exists in one of:
        -C:\IOT\Exes\apache-ant-1.8.2\lib
        -C:\Users\kwaghmode.ant\lib
        -a directory added on the command line with the -lib argument

Total time: 0 seconds

---

---

Am I missing something? Also links(on example page on github) 'Ant' and 'Maven' given in "See Ant or Maven for details about how to run the example." are not working.

Thanks for your help,
KW

**Comment by kedarwaghmode** [comment]
Ok. I was able to get those links working by replacing /aslakhellesoy/ with /cucumber/ in the browser address bar as suggested by mylene on thread of issue#108. But still no luck with this java example.

**Comment by josephks** [comment]
Try [my fork](https://github.com/josephks/cuke4duke). I updated the build.xml for the java example.

**Comment by kedarwaghmode** [comment]
Hi Joseph,

Thanks for your reply. I tried but it failed with error saying ".....examples\java\build.xml:19: Java returned: 1" and I think this is the cause "[cucumber] No such file or directory - target/junit-report/TEST-features\call_step.xml (Errno::ENOENT)".

Again I appreciate your help,
Kedar

**Comment by josephks** [comment]
What command did you run and what was the exact output?

**Comment by kedarwaghmode** [comment]
I executed "ant -Divy=true -Dgems=true" and I got following output

---

---

`````` download-ivy:
     [echo] installing ivy...
      [get] Getting: http://repo1.maven.org/maven2/org/apache/ivy/ivy/2.2.0/ivy-
2.2.0.jar
      [get] To: ..\josephks-cuke4duke-v0.4.4-6-g322666
e\josephks-cuke4duke-322666e\examples\java\lib_ivy\ivy.jar
      [get] Not modified - so not downloaded

install-ivy:

-download-jars:
[ivy:retrieve] :: Ivy 2.2.0 - 20100923230623 :: http://ant.apache.org/ivy/ ::
[ivy:retrieve] :: loading settings :: file = ..\joseph
ks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4duke-322666e\examples\java\ivysetti
ngs.xml
[ivy:retrieve] :: resolving dependencies :: cukes.info#java-example;working@iotu
ser-loaner
[ivy:retrieve]  confs: [default]
[ivy:retrieve]  found cuke4duke#cuke4duke;0.4.4 in cukes
[ivy:retrieve]  found org.jruby#jruby-complete;1.6.1 in ibiblio
[ivy:retrieve]  found org.picocontainer#picocontainer;2.11.2 in ibiblio
[ivy:retrieve]  found junit#junit;4.8.2 in ibiblio
[ivy:retrieve] :: resolution report :: resolve 257ms :: artifacts dl 16ms
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   4   |   0   |   0   |   0   ||   4   |   0   |
        ---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: cukes.info#java-example
[ivy:retrieve]  confs: [default]
[ivy:retrieve]  0 artifacts copied, 4 already retrieved (0kB/10ms)

-define-paths:

-compile-steps:
    [javac] ..\josephks-cuke4duke-v0.4.4-6-g322666e\jo
sephks-cuke4duke-322666e\examples\java\build.xml:11: warning: 'includeantruntime
' was not set, defaulting to build.sysclasspath=last; set to false for repeatabl
e builds

-install-gems:
      [gem]
      [gem] (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::
) (::)
      [gem]
      [gem] Thank you for installing cucumber-1.0.0.
      [gem] Please be sure to read http://wiki.github.com/cucumber/cucumber/upgr
ading
      [gem] for important information about this release. Happy cuking!
      [gem]
      [gem] (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::
) (::)
      [gem]
      [gem] Successfully installed cucumber-1.0.0
      [gem] 1 gem installed
      [gem] Successfully installed cuke4duke-0.4.4
      [gem] 1 gem installed

cucumber:
 [cucumber] Code:
 [cucumber]   * src/test/ruby/ruby_hook.rb
 [cucumber]   * target/test-classes/simple/CalledSteps.class
 [cucumber]   * target/test-classes/simple/CallingSteps.class
 [cucumber]   * target/test-classes/simple/ChineseCalculatorSteps.class
 [cucumber]   * target/test-classes/simple/HalfManualSteps.class
 [cucumber]   * target/test-classes/simple/HookSteps.class
 [cucumber]   * target/test-classes/simple/NorwegianSteps.class
 [cucumber]   * target/test-classes/simple/StuffSteps$1.class
 [cucumber]   * target/test-classes/simple/StuffSteps$2.class
 [cucumber]   * target/test-classes/simple/StuffSteps.class
 [cucumber]   * target/test-classes/simple/SuperSteps.class
 [cucumber]   * target/test-classes/simple/TransformSteps$Car.class
 [cucumber]   * target/test-classes/simple/TransformSteps$User.class
 [cucumber]   * target/test-classes/simple/TransformSteps.class
 [cucumber]
 [cucumber] Features:
 [cucumber]   * features/call_step.feature
 [cucumber]   * features/chinese_calculator.feature
 [cucumber]   * features/demo.feature
 [cucumber]   * features/half_manual.feature
 [cucumber]   * features/hooks.feature
 [cucumber]   * features/norwegian.feature
 [cucumber]   * features/transform.feature
 [cucumber] Parsing feature files took 0m0.231s
 [cucumber]
 [cucumber] Feature: Call steps
 [cucumber]   In order to reuse my steps
 [cucumber]   I, the programmer want to call them from a step definition by name

 [cucumber]
 [cucumber]   Scenario: Call a step?[90m      # features\call_step.feature:5?[0m

 [cucumber]     ?[32mWhen I call another step?[90m # CallingSteps.iCallAnotherSt
ep()?[0m?[0m
 [cucumber] No such file or directory - target/junit-report/TEST-features\call_s
tep.xml (Errno::ENOENT)
 [cucumber] org/jruby/RubyFile.java:441:in `initialize'
 [cucumber] org/jruby/RubyIO.java:1117:in `open'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/bin/../lib
/cucumber/formatter/junit.rb:152:in `write_file'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/bin/../lib
/cucumber/formatter/junit.rb:46:in `after_feature'
 [cucumber] org/jruby/RubyKernel.java:2056:in `send'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/tree_walker.rb:174:in `send_to_all'
 [cucumber] org/jruby/RubyArray.java:1602:in `each'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/tree_walker.rb:172:in `send_to_all'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/tree_walker.rb:165:in `broadcast'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/tree_walker.rb:19:in `visit_feature'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/features.rb:29:in `accept'
 [cucumber] org/jruby/RubyArray.java:1602:in `each'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/features.rb:17:in `each'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/features.rb:28:in `accept'
 [cucumber] ../josephks-cuke4duke-v0.    ?[32mThen mag
ic should happen?[90m # CalledSteps.magicShouldHappen()?[0m?[0m
 [cucumber]
 [cucumber] 4.4-6-g322666e/josephks-cuke4duke-322666e/examples/java/lib/.jruby/g
ems/cucumber-1.0.0/lib/cucumber/ast/tree_walker.rb:14:in `visit_features'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/tree_walker.rb:164:in `broadcast'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/ast/tree_walker.rb:13:in `visit_features'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/runtime.rb:45:in `run!'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/cli/main.rb:43:in `execute!'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/lib/cucumb
er/cli/main.rb:20:in `execute'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/bin/cucumb
er:14:in `(root)'
 [cucumber] org/jruby/RubyKernel.java:1063:in `load'
 [cucumber] ../josephks-cuke4duke-v0.4.4-6-g322666e/jo
sephks-cuke4duke-322666e/examples/java/lib/.jruby/gems/cucumber-1.0.0/bin/cucumb
er:4:in `(root)'
 [cucumber] org/jruby/RubyKernel.java:1063:in `load'
 [cucumber] ..\josephks-cuke4duke-v0.4.4-6-g322666e\jo
sephks-cuke4duke-322666e\examples\java\lib\.jruby\bin\cuke4duke:19:in `(root)'

BUILD FAILED
..\josephks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4
duke-322666e\examples\java\build.xml:19: Java returned: 1

Total time: 35 seconds

..\josephks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4
duke-322666e\examples\java>```

*********************************************************************************************************************************************
*********************************************************************************************************************************************

When I executed "mvn cuke4duke:cucumber", I got following output

******************************************************************************************************************************************
******************************************************************************************************************************************

```..\josephks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4
duke-322666e\examples\java>mvn cuke4duke:cucumber
[INFO] Scanning for projects...
Downloading: http://cukes.info/maven/org/apache/maven/plugins/maven-site-plugin/
3.0-beta-4-SNAPSHOT/maven-metadata.xml
Downloading: http://repository.apache.org/snapshots/org/apache/maven/plugins/mav
en-site-plugin/3.0-beta-4-SNAPSHOT/maven-metadata.xml
Downloaded: http://repository.apache.org/snapshots/org/apache/maven/plugins/mave
n-site-plugin/3.0-beta-4-SNAPSHOT/maven-metadata.xml (809 B at 3.3 KB/sec)
Downloading: http://cukes.info/maven/org/apache/maven/plugins/maven-site-plugin/
3.0-beta-4-SNAPSHOT/maven-site-plugin-3.0-beta-4-20110712.115141-32.pom
Downloading: http://repository.apache.org/snapshots/org/apache/maven/plugins/mav
en-site-plugin/3.0-beta-4-SNAPSHOT/maven-site-plugin-3.0-beta-4-20110712.115141-
32.pom
Downloaded: http://repository.apache.org/snapshots/org/apache/maven/plugins/mave
n-site-plugin/3.0-beta-4-SNAPSHOT/maven-site-plugin-3.0-beta-4-20110712.115141-3
2.pom (22 KB at 100.6 KB/sec)
Downloading: http://cukes.info/maven/org/apache/maven/plugins/maven-plugins/21/m
aven-plugins-21.pom
Downloading: http://repository.apache.org/snapshots/org/apache/maven/plugins/mav
en-plugins/21/maven-plugins-21.pom
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-plugin
s/21/maven-plugins-21.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-plugins
/21/maven-plugins-21.pom (13 KB at 26.6 KB/sec)
Downloading: http://cukes.info/maven/org/apache/maven/maven-parent/20/maven-pare
nt-20.pom
Downloading: http://repository.apache.org/snapshots/org/apache/maven/maven-paren
t/20/maven-parent-20.pom
Downloading: http://repo1.maven.org/maven2/org/apache/maven/maven-parent/20/mave
n-parent-20.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/maven-parent/20/maven
-parent-20.pom (25 KB at 72.2 KB/sec)
Downloading: http://cukes.info/maven/org/apache/apache/9/apache-9.pom
Downloading: http://repository.apache.org/snapshots/org/apache/apache/9/apache-9
.pom
Downloading: http://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom (15 K
B at 43.7 KB/sec)
Downloading: http://repository.apache.org/snapshots/org/apache/maven/plugins/mav
en-site-plugin/3.0-beta-4-SNAPSHOT/maven-site-plugin-3.0-beta-4-20110712.115141-
32.jar
Downloaded: http://repository.apache.org/snapshots/org/apache/maven/plugins/mave
n-site-plugin/3.0-beta-4-SNAPSHOT/maven-site-plugin-3.0-beta-4-20110712.115141-3
2.jar (112 KB at 275.2 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Cuke4Duke: Java Example 0.4.4
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- cuke4duke-maven-plugin:0.4.4:cucumber (default-cli) @ cuke4duke-java-
example ---
[INFO] Error opening script file: C:/Users/kwaghmode/.m2/repository/.jruby/bin/c
uke4duke (The system cannot find the path specified)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.659s
[INFO] Finished at: Wed Jul 13 09:53:53 PDT 2011
[INFO] Final Memory: 3M/122M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cuke4duke:cuke4duke-maven-plugin:0.4.4:cucumber (
default-cli) on project cuke4duke-java-example: JRuby failed. Java returned: 1 -
> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
..\josephks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4
duke-322666e\examples\java>```
*********************************************************************************************************************************************
*********************************************************************************************************************************************
And when I executed "mvn integration-test" and I got following errors 

*********************************************************************************************************************************************
*********************************************************************************************************************************************
```..\josephks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4
duke-322666e\examples\java>mvn integration-test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Cuke4Duke: Java Example 0.4.4
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ cuke4duk
e-java-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory ..\josephks
-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4duke-322666e\examples\java\src\main\r
esources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ cuke4duke-jav
a-example ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @
cuke4duke-java-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory ..\josephks
-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4duke-322666e\examples\java\src\test\r
esources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ cuke4
duke-java-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.7.2:test (default-test) @ cuke4duke-java-exam
ple ---
[INFO] Surefire report directory: ..\josephks-cuke4duk
e-v0.4.4-6-g322666e\josephks-cuke4duke-322666e\examples\java\target\surefire-rep
orts

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
There are no tests to run.

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ cuke4duke-java-example ---

[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO]
[INFO] >>> maven-source-plugin:2.1.2:jar (bind-sources) @ cuke4duke-java-example
 >>>
[INFO]
[INFO] <<< maven-source-plugin:2.1.2:jar (bind-sources) @ cuke4duke-java-example
 <<<
[INFO]
[INFO] --- maven-source-plugin:2.1.2:jar (bind-sources) @ cuke4duke-java-example
 ---
[INFO] No sources in project. Archive not created.
[INFO]
[INFO] --- cuke4duke-maven-plugin:0.4.4:cucumber (run-features) @ cuke4duke-java
-example ---
[INFO] Code:
[INFO]   * ../josephks-cuke4duke-v0.4.4-6-g322666e/jos
ephks-cuke4duke-322666e/examples/java/src/test/ruby/ruby_hook.rb
[INFO] uninitialized constant Cucumber::Ast::StepInvocation::BACKTRACE_FILTER_PA
TTERNS (NameError)
[INFO] org/jruby/RubyModule.java:2526:in `const_missing'
[INFO] ../.m2/repository/.jruby/gems/cuke4duke-0.4.4/bin/../lib/
cucumber/jvm_support/backtrace_filter.rb:1:in `(root)'
[INFO] org/jruby/RubyKernel.java:1038:in `require'
[INFO] file:/../.m2/repository/org/jruby/jruby-complete/1.6.1/jr
uby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/cust
om_require.rb:29:in `require'
[INFO] ../.m2/repository/.jruby/gems/cuke4duke-0.4.4/bin/../lib/
cucumber/jvm_support/backtrace_filter.rb:1:in `(root)'
[INFO] org/jruby/RubyKernel.java:1038:in `require'
[INFO] file:/../.m2/repository/org/jruby/jruby-complete/1.6.1/jr
uby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/cust
om_require.rb:29:in `require'
[INFO] ../.m2/repository/.jruby/gems/cuke4duke-0.4.4/bin/../lib/
cucumber/class_support/backtrace_filter.rb:7:in `cuke4!'
[INFO] ../.m2/repository/.jruby/gems/cuke4duke-0.4.4/bin/../lib/
cucumber/class_support/class_language.rb:3:in `(root)'
[INFO] org/jruby/RubyKernel.java:1038:in `require'
[INFO] file:/../.m2/repository/org/jruby/jruby-complete/1.6.1/jr
uby-complete-1.6.1.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/cust
om_require.rb:29:in `require'
[INFO] ../.m2/repository/.jruby/gems/cuke4duke-0.4.4/bin/../lib/
cucumber/class_support/class_language.rb:16:in `constantize'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime/support_code.rb:68:in `load_programming_language'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime/support_code.rb:190:in `programming_language_for'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime/support_code.rb:174:in `load_file'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime/support_code.rb:78:in `load_files!'
[INFO] org/jruby/RubyArray.java:1602:in `each'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime/support_code.rb:77:in `load_files!'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime.rb:137:in `load_step_definitions'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/runtime.rb:39:in `run!'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/cli/main.rb:43:in `execute!'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/lib/cucumber
/cli/main.rb:20:in `execute'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/bin/cucumber
:14:in `(root)'
[INFO] org/jruby/RubyKernel.java:1063:in `load'
[INFO] ../.m2/repository/.jruby/gems/cucumber-1.0.1/bin/cucumber
:4:in `(root)'
[INFO] org/jruby/RubyKernel.java:1063:in `load'
[INFO] ..\.m2\repository\.jruby\bin\cuke4duke:19:in `(root)'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.092s
[INFO] Finished at: Wed Jul 13 09:59:43 PDT 2011
[INFO] Final Memory: 6M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cuke4duke:cuke4duke-maven-plugin:0.4.4:cucumber (
run-features) on project cuke4duke-java-example: JRuby failed. Java returned: 1
-> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
..\josephks-cuke4duke-v0.4.4-6-g322666e\josephks-cuke4
duke-322666e\examples\java>```

********************************************************************************************************************************************
********************************************************************************************************************************************
``````

**Comment by kedarwaghmode** [comment]
I am sorry for this hard to read output. Let me know if you want me to upload it somewhere.

Thanks for your help,
Kedar

**Comment by josephks** [comment]
Yes makrdown did a number on your output.  Try surrounding all of that with &lt;code&gt; and see if that helps (you can preview to see if it works)

I don't know about the maven commands, but running with ant does work.  The jars are downloaded and the gems are installed.  It seems as if one of the actual tests is failing.  I wonder if it is a windows problem, in that the right directory is not  being created because something is using a / instead of a \ .

I'm getting a different problem on linux.  The examples run but cucumber hangs.  I'll open a separate issue for that.

When you run with maven it is running into issue 118, which is why in my build.xml I explicitly install the cucumber 1.0.0 gem.  I don't know how to fix the maven run.

**Comment by josephks** [comment]
Actually instead of &lt;code&gt; use the three backticks.  You can edit your comment by bringing the mouse cursor to the upper right corner of the comment.

**Comment by kedarwaghmode** [comment]
Thanks Joseph. Hope updated output is readable now.
