### ISSUE TITLE
Example project 'jamesladd-maven-cuke4duke-jump-start' fails

### ISSUE THREAD

**Issue by belgoros** [cucumber-attic/cuke4duke#128]
I downloaded the above project, unzipped it to a folder and tried to run Maven as explained in the project's README file:

```
mvn -Dcucumber.installGems=true cuke4duke:cucumber
```

The error stack trace:

```
C:\Documents and Settings\A187589\Mes documents\ror\jamesladd-maven-cuke4duke-jump-start>mvn -Dcucumber.installGems=true cuke4duke
:cucumber
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.mycompany.app:my-webapp:war:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 62, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building my-webapp Maven Webapp 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- cuke4duke-maven-plugin:0.4.4:cucumber (default-cli) @ my-webapp ---
[INFO] Successfully installed cuke4duke-0.4.2
[INFO] 1 gem installed
[INFO] Code:
[INFO]
[INFO] Features:
[INFO] No such file or directory - and (Errno::ENOENT)
[INFO] org/jruby/RubyFile.java:441:in `initialize'
[INFO] org/jruby/RubyIO.java:1117:in `open'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/feature_file.rb:53:in `source'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/feature_file.rb:35:in `parse'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime/features_loader.rb:28:in `
load'
[INFO] org/jruby/RubyArray.java:1602:in `each'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime/features_loader.rb:26:in `
load'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime/features_loader.rb:14:in `
features'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime.rb:132:in `features'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime.rb:45:in `run!'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/cli/main.rb:48:in `execute!'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/cli/main.rb:21:in `execute'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/bin/cucumber:8:in `(root)'
[INFO] org/jruby/RubyKernel.java:1063:in `load'
[INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/bin/cucumber:4:in `(root)'
[INFO] org/jruby/RubyKernel.java:1063:in `load'
[INFO] C:\Documents and Settings\A187589\.m2\repository\.jruby\bin\cuke4duke:19:in `(root)'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.739s
[INFO] Finished at: Tue Nov 22 09:27:10 CET 2011
[INFO] Final Memory: 4M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cuke4duke:cuke4duke-maven-plugin:0.4.4:cucumber (default-cli) on project my-webapp: JRuby failed. J
ava returned: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
C:\Documents and Settings\A187589\Mes documents\ror\jamesladd-maven-cuke4duke-jump-start>
```

I got it on a Windows XP PC:
jruby 1.6.5 (ruby-1.8.7-p330) (2011-10-25 9dcd388) (Java HotSpot(TM) Client VM 1.6.0_27) [Windows XP-x86-java]

More of that, the link to Maven https://github.com/aslakhellesoy/cuke4duke/wiki/maven is broken on the project examples page:
https://github.com/cucumber/cuke4duke/tree/master/examples/java

**Comment by aslakhellesoy** [comment]
On Tue, Nov 22, 2011 at 8:33 AM, Serguei Cambour
reply@reply.github.com
wrote:

> I downloaded the above project, unzipped it to a folder and tried to run Maven as explained in the project's README file:
> 
> ```
> mvn -Dcucumber.installGems=true cuke4duke:cucumber
> ```
> 
> The error stack trace:
> 
> ```
> C:\Documents and Settings\A187589\Mes documents\ror\jamesladd-maven-cuke4duke-jump-start>mvn -Dcucumber.installGems=true cuke4duke
> :cucumber
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.mycompany.app:my-webapp:war:0.0.1-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 62, column 15
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building my-webapp Maven Webapp 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- cuke4duke-maven-plugin:0.4.4:cucumber (default-cli) @ my-webapp ---
> [INFO] Successfully installed cuke4duke-0.4.2
> [INFO] 1 gem installed
> [INFO] Code:
> [INFO]
> [INFO] Features:
> [INFO] No such file or directory - and (Errno::ENOENT)
> [INFO] org/jruby/RubyFile.java:441:in `initialize'
> [INFO] org/jruby/RubyIO.java:1117:in `open'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/feature_file.rb:53:in `source'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/feature_file.rb:35:in `parse'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime/features_loader.rb:28:in `
> load'
> [INFO] org/jruby/RubyArray.java:1602:in `each'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime/features_loader.rb:26:in `
> load'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime/features_loader.rb:14:in `
> features'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime.rb:132:in `features'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/runtime.rb:45:in `run!'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/cli/main.rb:48:in `execute!'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/lib/cucumber/cli/main.rb:21:in `execute'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/bin/cucumber:8:in `(root)'
> [INFO] org/jruby/RubyKernel.java:1063:in `load'
> [INFO] C:/Documents and Settings/A187589/.m2/repository/.jruby/gems/cucumber-0.9.4/bin/cucumber:4:in `(root)'
> [INFO] org/jruby/RubyKernel.java:1063:in `load'
> [INFO] C:\Documents and Settings\A187589\.m2\repository\.jruby\bin\cuke4duke:19:in `(root)'
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 25.739s
> [INFO] Finished at: Tue Nov 22 09:27:10 CET 2011
> [INFO] Final Memory: 4M/123M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal cuke4duke:cuke4duke-maven-plugin:0.4.4:cucumber (default-cli) on project my-webapp: JRuby failed. J
> ava returned: 1 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> C:\Documents and Settings\A187589\Mes documents\ror\jamesladd-maven-cuke4duke-jump-start>
> ```
> 
> I got it on a Windows XP PC:
> jruby 1.6.5 (ruby-1.8.7-p330) (2011-10-25 9dcd388) (Java HotSpot(TM) Client VM 1.6.0_27) [Windows XP-x86-java]

Please see http://groups.google.com/group/cukes/browse_thread/thread/299d94d38500e8c3

> More of that, the link to Maven is broken on the project examples page:
> https://github.com/cucumber/cuke4duke/tree/master/examples/java

Fixed the links.

**Comment by belgoros** [comment]
Thanks a lot, Aslak! I was not aware that cuek4duke was KO. I downloaded the cucumber-jvm zip and tried the calculator example. I had to modify the main pom in 'cucumber-cucumber-jvm' project as follows:

```
<repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
        <!--
        <repository>
            <id>codehaus</id>
            <url>http://repository.codehaus.org</url>
        </repository>
        -->
```

As you see I commented the codehouse repository, - without that Maven could not download 'cucumber-java' jar.
Running 

```
mvn test
```

on 'java-calculator' project was successful.
Thanks again for your help.

**Comment by belgoros** [comment]
Hi Aslak,

One more question that for which I didn't didn't find the response.
Is it posible to use somehow 'capybara' and 'factory_girl_rails' gems with
cucumber-jvm to simulate somehow calls to database, browser behavior, etc.
Or as you explianed somewhere, there is no Ruby, just Java.
Or may you know a better way to simultae the above things as we usually do
it in RoR?

Thank you in advance.

Serguei

On Tue, Nov 22, 2011 at 10:32 AM, Aslak Hellesøy <
reply@reply.github.com

**Comment by aslakhellesoy** [comment]
On Tue, Nov 22, 2011 at 2:48 PM, Serguei Cambour
reply@reply.github.com
wrote:

> Hi Aslak,
> 
> One more question that for which I didn't didn't find the response.
> Is it posible to use somehow 'capybara' and 'factory_girl_rails' gems with
> cucumber-jvm to simulate somehow calls to database, browser behavior, etc.

Capybara is a browser automation tool. It can't talk to a database.
The Capybara equivalent for the JVM is Selenium WebDriver. See the
https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-webbit-websockets-selenium
for an example

> Or as you explianed somewhere, there is no Ruby, just Java.

Then I suggest you use Cucumber-JVM with Java step definitions.

Aslak

**Comment by belgoros** [comment]
Thanks again for your response.
Yes, I've just run Cucumber with JVM. I think about use Cucumber on an
existing java web application based on Maven, Spring and Tapestry and Jetty
(or Tomcat). That's why I'm searching the more appropriate solution to
simulate something I did in Rails by using Cucumber, RSpec,
factory-girl_rails and capybara.
I'll try to do something with Selenium WebDriver.

Thank you very much and sorry for my typos :).

On Tue, Nov 22, 2011 at 5:10 PM, Aslak Hellesøy <
reply@reply.github.com
