### ISSUE TITLE
cuke4duke install fails

### ISSUE THREAD

**Issue by mikesteez** [cucumber-attic/cuke4duke#129]
Cuke4duke won't install.

Failed to run gem with arguments: install cuke4duke --version 0.4.4
at cuke4duke.ant.GemTask.execute(GemTask.java:24)

Because of

[INFO] [cuke4duke:cucumber {execution: run-features}]
[INFO] System.java:-2:in arraycopy': java.lang.ArrayIndexOutOfBoundsException
[INFO] from DefaultResolver.java:111:inmakeTime'
[INFO] from DefaultResolver.java:277:in `create'

I think this is related to the date-bug in JRuby, http://jira.codehaus.org/browse/JRUBY-5581

An upgrade to a more current JRuby, 1.6.2 or above, which has the fix for the issue might solve this.

To reproduce, install https://github.com/jamesladd/maven-cuke4duke-jump-start and run

mvn -Dcucumber.installGems=true cuke4duke:cucumber

**Comment by trnl** [comment]
Mike, you are right. Using jruby-1.6.5 fixed this issue for me.

-vova

**Comment by darrellme** [comment]
Vova, I tried upgrading to 1.6.5 of JRuby, however this gave me another issue: - 

Any ideas ?

-install-gems:
      [gem](::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)
      [gem] Thank you for installing cucumber-1.1.4.
      [gem] Please be sure to read http://wiki.github.com/cucumber/cucumber/upgrading
      [gem] for important information about this release. Happy cuking!
      [gem](::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)
      [gem] Successfully installed json-1.6.4-java
      [gem] Successfully installed gherkin-2.7.2-java
      [gem] Successfully installed term-ansicolor-1.0.7
      [gem] Successfully installed builder-3.0.0
      [gem] Successfully installed diff-lcs-1.1.3
      [gem] Successfully installed cucumber-1.1.4
      [gem] Successfully installed cuke4duke-0.4.4
      [gem] 7 gems installed
-cucumber-specific-host:
-cucumber-no-host:
     [echo] cucumber-no-host
 [cucumber] Code:
 [cucumber]   \* build/classes/test/com/sap/wcms/authentication/test/steps/DummyStep.class
 [cucumber] Features:
 [cucumber]   \* features/wcms_quicktest.feature
 [cucumber] Parsing feature files took 0m0.069s
 [cucumber] Feature: WCMS UI features
 [cucumber]   In order to ensure that the WCMS features are working correctly
 [cucumber]   As a developer
 [cucumber]   I want to test the UI functionality
 [cucumber]   Scenario: :Log onto wcms                  # features/wcms_quicktest.feature:6
 [cucumber]     Given The action is logon to wcms       # features/wcms_quicktest.feature:7
 [cucumber]     When the user is admin                  # features/wcms_quicktest.feature:8
 [cucumber] undefined method `create_step_match' for #<#<Module:0x1476ff9e0>::ClassLanguage:0x7c198046> (NoMethodError)
 [cucumber] org/jruby/RubyKernel.java:2067:in`send'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:148:in `matches'
 [cucumber] org/jruby/RubyArray.java:2336:in`collect'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:147:in `matches'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:133:in`step_match'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:66:in `step_match'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/step_invocation.rb:82:in`find_step_match!'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/step_invocation.rb:55:in `invoke'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/step_invocation.rb:38:in`accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:99:in `visit_step'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:163:in`broadcast'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:98:in `visit_step'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/step_collection.rb:15:in`accept'
 [cucumber] org/jruby/RubyArray.java:1602:in `each'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/step_collection.rb:14:in`accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:93:in `visit_steps'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:163:in`broadcast'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:92:in `visit_steps'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/scenario.rb:55:in`accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:80:in `with_hooks'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:96:in`before_and_after'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:79:in `with_hooks'
 [cucumber] org/jruby/RubyProc.java:268:in`call'
 [cucumber] org/jruby/RubyProc.java:228:in `call'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:120:in`around'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/language_support/language_methods.rb:9:in `around'
 [cucumber] org/jruby/RubyProc.java:268:in`call'
 [cucumber] org/jruby/RubyProc.java:228:in `call'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/language_support/language_methods.rb:91:in`execute_around'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/language_support/language_methods.rb:8:in `around'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:119:in`around'
 [cucumber] org/jruby/RubyProc.java:268:in `call'
 [cucumber] org/jruby/RubyProc.java:228:in`call'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:117:in `around'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:91:in`around'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:78:in `with_hooks'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/scenario.rb:53:in`accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/scenario.rb:108:in `with_visitor'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/scenario.rb:47:in`accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:51:in `visit_feature_element'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:163:in`broadcast'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:50:in `visit_feature_element'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/feature.rb:43:in`accept'
 [cucumber] org/jruby/RubyArray.java:1602:in `each'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/feature.rb:42:in`accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:20:in `visit_feature'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:163:in`broadcast'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:19:in `visit_feature'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/features.rb:29:in`accept'
 [cucumber] org/jruby/RubyArray.java:1602:in `each'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/features.rb:17:in`each'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/features.rb:28:in `accept'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:14:in`visit_features'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:163:in `broadcast'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/ast/tree_walker.rb:13:in`visit_features'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:46:in `run!'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/cli/main.rb:43:in`execute!'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/lib/cucumber/cli/main.rb:20:in `execute'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/bin/cucumber:14:in`(root)'
 [cucumber] org/jruby/RubyKernel.java:1063:in `load'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/gems/cucumber-1.1.4/bin/cucumber:4:in`(root)'
 [cucumber] org/jruby/RubyKernel.java:1063:in `load'
 [cucumber] /Users/i022141/github/shared/osgi/com.sap.wcms.authenticator.cps/lib/.jruby/bin/cuke4duke:19:in`(root)'

**Comment by trnl** [comment]
Hey, try to use cuke4duke 0.4.4

Are you using maven?

-vova

**Comment by darrellme** [comment]
Hi

I'm already using 0.4.4.

I'm using ANT as opposed to Maven currently, this may change in the future, but for now we have to stick with ANT. 

Thanks

D

**Comment by trnl** [comment]
I've remembered

the problem now in compatibility between cucumber 1.1.4 and cuke4duke 0.4.4

I've solved it with removing cucumber 1.1.4 gem. installing 1.1.2 and renaming 1.1.2 to 1.1.4. I've done this in m2 repository.
some information here:
http://groups.google.com/group/cukes/browse_thread/thread/0c2e40902e135b5d

-vova

**Comment by darrellme** [comment]
I've managed to find the problem, and I've created an issue against the cucumber repository as they have removed a method create_step_match from one of their .rb files since 1.1.3.

The other way around this is to use the gem install command and install cucumber 1.1.2 before installing cuke4duke and hey presto it works.

Just thought you might like to know

D
