### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by ittayd** [cucumber-attic/cuke4duke#22]
<pre>
.../cuke4duke (master) > mvn install
....
.../cuke4duke (master) > cd examples/spring
..les/spring (master) > mvn integration-test
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Cuke4Duke Spring Example
[INFO]    task-segment: [integration-test]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Nothing to compile - all classes are up to date
[INFO] [resources:testResources {execution: default-testResources}]
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] [compiler:testCompile {execution: default-testCompile}]
[INFO] Nothing to compile - all classes are up to date
[INFO] [surefire:test {execution: default-test}]
[INFO] Surefire report directory: /work/research/cuke4duke/examples/spring/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
There are no tests to run.

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] [jar:jar {execution: default-jar}]
[INFO] [cuke4duke:features {execution: run-features}]
[INFO] Error opening script file: /work/maven/repository/.gem/bin/cucumber (No such file or directory)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Java returned: 1
[INFO] ------------------------------------------------------------------------
[INFO] Trace
Java returned: 1
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:87)
    at cuke4duke.mojo.CucumberMojo.execute(CucumberMojo.java:80)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Tue Sep 15 07:31:02 IDT 2009
[INFO] Final Memory: 14M/119M
[INFO] ------------------------------------------------------------------------
</pre>

**Comment by aslakhellesoy** [comment]
You have to install the cucumber gem too (the first time you run at least).

```
cd examples/spring
mvn integration-test -Dcucumber.installGems=true
```

This is documented in the [Maven](http://wiki.github.com/aslakhellesoy/cuke4duke/maven) page in the Wiki

**Comment by fabianbuch** [comment]
you didn't install the cucumber gem, try:

```
mvn -Dcucumber.installGems=true cuke4duke:features
```

(follow http://wiki.github.com/aslakhellesoy/cuke4duke/maven)

**Comment by ittayd** [comment]
closed due to RTFM

**Comment by aslakhellesoy** [comment]
Closed per request

**Comment by ittayd** [comment]
still no cigar

<pre>
...les/simple (master) > mvn -Dcucumber.installGems=true cuke4duke:features
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Cuke4Duke Simple Example
[INFO]    task-segment: [cuke4duke:features]
[INFO] ------------------------------------------------------------------------
[INFO] [cuke4duke:features {execution: default-cli}]
[WARNING] JRuby limited openssl loaded. gem install jruby-openssl for full support.
[WARNING] http://wiki.jruby.org/wiki/JRuby_Builtin_OpenSSL
[WARNING] ERROR:  could not find gem cucumber locally or in a repository
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Java returned: 2
[INFO] ------------------------------------------------------------------------
[INFO] Trace
Java returned: 2
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:87)
    at cuke4duke.mojo.AbstractJRubyMojo.installGem(AbstractJRubyMojo.java:180)
    at cuke4duke.mojo.CucumberMojo.execute(CucumberMojo.java:66)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21 seconds
[INFO] Finished at: Tue Sep 15 15:01:27 IDT 2009
[INFO] Final Memory: 4M/75M
[INFO] ------------------------------------------------------------------------
</pre>

**Comment by ittayd** [comment]
i did 'gem fetch cucmber -v0.3.100' and ran maven again and it found the gem locally

**Comment by aslakhellesoy** [comment]
Did you get cuke4duke running now? If not, please ask on the mailing list, where more people can help you out.

**Comment by ittayd** [comment]
i did, but it's an ugly workaround

**Comment by aslakhellesoy** [comment]
See you on the mailing list then. I'm pretty sure this isn't a bug, but something wrong on your side. Please restate the problem and link to a http://gist.github.com/ that contains the output. Create another gist with output passing -X to maven. Also please read this: http://wiki.github.com/aslakhellesoy/cucumber/contributing

**Comment by aslakhellesoy** [comment]
Turns out this is a rubygems+gemcutter bug: http://groups.google.com/group/cukes/browse_thread/thread/fc9809247b3369f5

**Comment by aslakhellesoy** [comment]
Fixed: http://github.com/aslakhellesoy/cuke4duke/commit/1a8671d4fcaeeb5fff86db47e4334dd8b7774de8
