### ISSUE TITLE
Need cuke4duke.jar files prior to version 0.4.3

### ISSUE THREAD

**Issue by cuke4duke** [cucumber-attic/cuke4duke#96]
I am using the following on Windows XP Professional.
jjruby 1.5.6 (ruby 1.8.7 patchlevel 249) (2010-12-03 9cf97c3) (Java HotSpot(TM) Client VM 1.6.0_18) [x86-java]

The gems installed are the following
cucumber-0.10.0.gem
json-1.4.6-java.gem
diff-lcs-1.1.2.gem
builder-2.1.2.gem
term-ansicolor-1.0.5.gem
gherkin-2.3.2-java.gem
jruby-0.0.1.gem

The cuke4duke jar file using is : cuke4duke-0.4.3.jar

When I run the cucumber tests through ant, the following error is diplayed:
{However the tests run fine if cuke4duke-0.3.0.beta.2.jar is used}
     [java] stack level too deep (SystemStackError)
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/formatter/html.rb:245:in `after_step_result'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/builder-2.1.2/lib/builder/xmlbase.rb:134:in`call'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/builder-2.1.2/lib/builder/xmlbase.rb:134:in `_nested_structures'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/builder-2.1.2/lib/builder/xmlbase.rb:58:in`method_missing'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/formatter/html.rb:244:in `after_step_result'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:174:in`send_to_all'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:172:in `each'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:172:in`send_to_all'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:165:in `broadcast'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:104:in`visit_step_result'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/step_invocation.rb:50:in `visit_step_result'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/step_invocation.rb:43:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:99:in `visit_step'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:164:in`broadcast'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:98:in `visit_step'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/step_collection.rb:15:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/step_collection.rb:14:in `each'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/step_collection.rb:14:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:93:in `visit_steps'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:164:in`broadcast'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:92:in `visit_steps'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/scenario.rb:53:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime.rb:79:in `with_hooks'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime.rb:95:in`before_and_after'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime.rb:78:in `with_hooks'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime/support_code.rb:112:in`call'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime/support_code.rb:112:in `around'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime.rb:90:in`around'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime.rb:77:in `with_hooks'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/scenario.rb:51:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/scenario.rb:106:in `with_visitor'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/scenario.rb:45:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:51:in `visit_feature_element'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:164:in`broadcast'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:50:in `visit_feature_element'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/feature.rb:40:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/feature.rb:39:in `each'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/feature.rb:39:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:20:in `visit_feature'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:164:in`broadcast'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:19:in `visit_feature'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/features.rb:29:in`accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/features.rb:17:in `each'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/features.rb:17:in`each'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/features.rb:28:in `accept'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:14:in`visit_features'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:164:in `broadcast'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/ast/tree_walker.rb:13:in`visit_features'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/runtime.rb:45:in `run!'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/cli/main.rb:43:in`execute!'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/cli/main.rb:20:in `execute'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/cucumber:14
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/lib/ruby/gems/1.8/gems/cucumber-0.10.0/bin/cucumber:19:in`load'
     [java] C:/Download/jruby-bin-1.5.6/jruby-1.5.6/bin/cucumber:19
     [java] Java Result: 1

**Comment by cuke4duke** [comment]
I am using only jruby (no ruby is installed on my system)

**Comment by prusswan** [comment]
yes, version 0.4.2 will be helpful because this is the only version that works on XP now

**Comment by cuke4duke** [comment]
Either could you please provide version 0.4.2 {or any other latest version which works on XP} or release 0.4.4 which will fix this issue.   I googled for versions prior to 0.4.3, but could not find any site where these jar files are available.

**Comment by prusswan** [comment]
0.4.2 is available in the discussion thread https://github.com/aslakhellesoy/cuke4duke/issues/closed#issue/93

I found a better solution though: add jruby 1.6.0 as a dependency to override 1.5.6 used by 0.4.3

**Comment by cuke4duke** [comment]
I am now using jruby 1.6.0 & cucumber 0.10.2.  So  now, do I have to configure any dependency stuff.

In the discussion thread I was not able to find the 0.4.2 jar file links.   The only links I could find were the following:
http://oc.rynning.no/cuke4duke-0.4.2.tgz (may be my own custom build) 
http://oc.rynning.no/cuke4duke-maven-plugin-0.4.2.tgz (as above) 
But they were not jar files

**Comment by prusswan** [comment]
okay, as I discovered jruby 1.6.0 resolves this problem with cuke4duke 0.4.3 not working on XP:
http://stackoverflow.com/questions/5017628/cucumber-0-4-3-cuke4duke-with-java-maven-gem-issues, but from your error I think you may have another problem here so I can't guarantee that your problems will go away even after specifying jruby 1.6.0 in pom.xml 

For the 0.4.2 jar files, you can compile them yourself from sources, or find them in http://oc.rynning.no/cuke4duke-0.4.2.tgz (unpack it)

**Comment by cuke4duke** [comment]
From the http://oc.rynning.no/cuke4duke-0.4.2.tgz, I am still not able to get the cuke4duke-0.4.2.jar file required for Windows XP.   Appreciate if you could extract the jar file and mail it to shenoy.venugopal@gmail.com.
