### ISSUE TITLE
Issue with cuke4duke using Eclipse/Spring/Maven

### ISSUE THREAD

**Issue by shisamud** [cucumber-attic/cuke4duke#98]
Hi,

I am trying to get familiar with cuke4duke for running Cucumber tests in Java. I have installed the example from "https://github.com/aslakhellesoy/cuke4duke/tree/master/examples/spring" but when I run "mvn -e integration-test" on the project, I am getting the following error. I'd appreciate your help with resolving this issue.

I am using Eclipse IDE with Maven plug-in and Spring framework. I noticed that "C:\Documents and Settings\hisamusm.m2\repository.jruby" directory is empty. This looks similar to the issue posted in "https://github.com/aslakhellesoy/cuke4duke/issues/closed#issue/80" but I am unable to resolve the error. I have looked at various other posts also but no luck.

I have tried running the "mvn -e integration-test" command from the Eclipse IDE and also directly from command line in Windows (DOS).

I also tried the "mvn -Dcucumber.installGems=true cuke4duke:cucumber -e" command but I get the same erorr. For some reason, "C:\Documents and Settings\hisamusm.m2\repository.jruby" directory is empty.

I am not sure if JRuby needs to be installed for cuke4duke to be run from Eclipse IDE but I tried installing JRuby also and I still get the same error.

Error Log:
- Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] ------------------------------------------------------------------------
  [INFO] Building Cuke4Duke: Spring Example
  [INFO] 
  [INFO] Id: cuke4duke:cuke4duke-spring-example:jar:0.4.3
  [INFO] task-segment: [integration-test]
  [INFO] ------------------------------------------------------------------------
  [INFO] Attempting to resolve a version for plugin: cuke4duke:cuke4duke-maven-plugin using meta-version: LATEST
  [INFO] artifact cuke4duke:cuke4duke-maven-plugin: checking for updates from codehaus
  [INFO] artifact cuke4duke:cuke4duke-maven-plugin: checking for updates from cukes
  [INFO] artifact cuke4duke:cuke4duke-maven-plugin: checking for updates from central
  [INFO] Attempting to resolve a version for plugin: cuke4duke:cuke4duke-maven-plugin using meta-version: RELEASE
  [INFO] Using version: 0.4.3 of plugin: cuke4duke:cuke4duke-maven-plugin
  [INFO] [resources:resources]
  [INFO] Using default encoding to copy filtered resources.
  [INFO] [compiler:compile]
  [INFO] Nothing to compile - all classes are up to date
  [INFO] [resources:testResources]
  [INFO] Using default encoding to copy filtered resources.
  [INFO] [compiler:testCompile]
  [INFO] Nothing to compile - all classes are up to date
  [INFO] [surefire:test]
  [INFO] Surefire report directory: C:\myprograms\java_apps\cuke4duke-spring-example\target\surefire-reports

---
##  T E S T S

There are no tests to run.

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] [jar:jar]
[INFO] [source:jar]
[INFO] Building jar: C:\myprograms\java_apps\cuke4duke-spring-example\target\cuke4duke-spring-example-0.4.3-sources.jar
[INFO] [cuke4duke:cucumber]
[INFO] Error opening script file: C:/Documents and Settings/hisamusm/.m2/repository/.jruby/bin/cuke4duke (The system cannot find the path specified)
[ERROR] 

The following mojo encountered an error while executing:
Group-Id: cuke4duke
Artifact-Id: cuke4duke-maven-plugin
Version: 0.4.3
Mojo: cucumber
brought in via: POM

While building project:
Group-Id: cuke4duke
Artifact-Id: cuke4duke-spring-example
Version: 0.4.3
From file: C:\myprograms\java_apps\cuke4duke-spring-example\pom.xml
Reason: JRuby failed.

Java returned: 1
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
    at cuke4duke.ant.JRubyTask.execute(JRubyTask.java:22)
    at cuke4duke.ant.CucumberTask.execute(CucumberTask.java:15)
    at cuke4duke.mojo.CucumberMojo.execute(CucumberMojo.java:84)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:579)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:265)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:191)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
    at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
    at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
    at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:904)
    at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:304)
    at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

Error stacktrace:
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'cuke4duke:cuke4duke-maven-plugin:0.4.3:cucumber': Mojo execution failed.
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:505)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:265)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:191)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
    at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
    at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
    at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:904)
    at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:304)
    at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
Caused by: org.apache.maven.plugin.PluginExecutionException: Mojo execution failed.
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:601)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
    ... 20 more
Caused by: org.apache.maven.plugin.MojoExecutionException: JRuby failed.
    at cuke4duke.mojo.CucumberMojo.execute(CucumberMojo.java:87)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:579)
    ... 21 more
Caused by: Java returned: 1
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
    at cuke4duke.ant.JRubyTask.execute(JRubyTask.java:22)
    at cuke4duke.ant.CucumberTask.execute(CucumberTask.java:15)
    at cuke4duke.mojo.CucumberMojo.execute(CucumberMojo.java:84)
    ... 22 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILED
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8 seconds
[INFO] Finished at: Tue Jan 25 15:06:59 CST 2011
[INFO] Final Memory: 2M/15M
[INFO] ------------------------------------------------------------------------

**Comment by shisamud** [comment]
Can someone please respond to this? We are trying to evaluate using Cucumber on our projects and if we cannot even get the basic examples to work, then it is difficult to justify using it.
